name: translation_script
description: The linum translation script.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  http: ^0.13.5
  path: ^1.8.2
  tuple: ^2.0.1
